# GET 
GET http://localhost:3001/api/contacts
Content-Type: application/json

###

# GET by id
GET http://localhost:3001/api/contacts/2
Content-Type: application/json

###

# POST
POST http://localhost:3001/api/contacts
Content-Type: application/json

{
  "id": 10,
  "firstname": "Adibou",
  "lastname": "Test",
  "email": "adibou@test.fr",
  "address": "Rue du Dev"
}

###

# PUT
PUT http://localhost:3001/api/contacts/2
Content-Type: application/json

{
  "id": 2,
  "firstname": "John",
  "lastname": "Doe",
  "email": "john.doe@test.fr",
  "address": "42 rue de Coda"
}

###

# DELETE
DELETE http://localhost:3001/api/contacts/1
Content-Type: application/json